export const colors = {
  primary: '#DA3C57',
  primaryDark: '#B72249',
  primaryLight: '#F16A82',
  primaryGradient: ['#F16A82', '#DA3C57'],
  secondary: '#F4C7D0',
  accent: '#FF9F0A',
  success: '#34C759',
  successLight: '#E8F9ED',
  successGradient: ['#5FD37A', '#34C759'],
  error: '#FF453A',
  errorLight: '#FEECEC',
  errorGradient: ['#FF6B60', '#FF453A'],
  warning: '#FF9F0A',
  warningLight: '#FFF3E2',
  warningGradient: ['#FFB340', '#FF9F0A'],
  info: '#F28CA0',
  infoLight: '#FFF0F3',
  infoGradient: ['#F6B1BE', '#F28CA0'],
  black: '#000000',
  white: '#FFFFFF',
  gray: '#8E8E93',
  grayLight: '#F2F2F7',
  grayLighter: '#FAFAFC',
  grayDark: '#48484A',
  text: '#111827',
  textSecondary: '#6B7280',
  textTertiary: '#9CA3AF',
  background: '#FBF6F8',
  card: '#FFFFFF',
  cardSecondary: '#F8EDF0',
  border: '#F0D9DF',
  borderLight: '#F6E8EC',
  green: '#34C759',
  greenLight: '#E8F9ED',
  overlay: 'rgba(15, 23, 42, 0.45)',
  shadow: 'rgba(15, 23, 42, 0.08)',
  taxi: '#DA3C57',
  food: '#34C759',
  market: '#F28CA0',
  pharmacy: '#FF453A',
  grocery: '#D95C73',
  gifts: '#C45586',
  electronics: '#9B5068',
  fashion: '#F16A82',
  glass: 'rgba(255, 255, 255, 0.72)',
  glassBorder: 'rgba(255, 255, 255, 0.55)',
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  xxxl: 64,
};

export const fonts = {
  regular: 'Cairo_400Regular',
  semiBold: 'Cairo_600SemiBold',
  bold: 'Cairo_700Bold',
  family: 'Cairo_400Regular',
};

export const typography = {
  display: {
    fontSize: 34,
    fontFamily: fonts.bold,
    lineHeight: 42,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  h1: {
    fontSize: 28,
    fontFamily: fonts.bold,
    lineHeight: 36,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  h2: {
    fontSize: 22,
    fontFamily: fonts.bold,
    lineHeight: 30,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  h3: {
    fontSize: 18,
    fontFamily: fonts.semiBold,
    lineHeight: 26,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  body: {
    fontSize: 16,
    fontFamily: fonts.regular,
    lineHeight: 24,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  bodySmall: {
    fontSize: 14,
    fontFamily: fonts.regular,
    lineHeight: 20,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  caption: {
    fontSize: 12,
    fontFamily: fonts.regular,
    lineHeight: 16,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  button: {
    fontSize: 16,
    fontFamily: fonts.semiBold,
    lineHeight: 22,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  label: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    lineHeight: 20,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
};

export const borderRadius = {
  sm: 8,
  md: 12,
  lg: 18,
  xl: 24,
  full: 9999,
};

export const shadows = {
  sm: {
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  md: {
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  lg: {
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  xl: {
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  float: {
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
};
