export const Services = [
  {
    id: 'ride',
    name: 'Ride',
    description: 'Book a ride',
    icon: 'car',
    color: '#3B82F6',
    gradient: ['#3B82F6', '#2563EB'],
  },
  {
    id: 'food',
    name: 'Food',
    description: 'Order food',
    icon: 'utensils',
    color: '#F97316',
    gradient: ['#F97316', '#EA580C'],
  },
  {
    id: 'grocery',
    name: 'Grocery',
    description: 'Grocery delivery',
    icon: 'shopping-cart',
    color: '#22C55E',
    gradient: ['#22C55E', '#16A34A'],
  },
  {
    id: 'courier',
    name: 'Courier',
    description: 'Send packages',
    icon: 'package',
    color: '#8B5CF6',
    gradient: ['#8B5CF6', '#7C3AED'],
  },
];

export const VehicleTypes = [
  {
    id: 'economy',
    name: 'Economy',
    description: 'Affordable rides',
    icon: 'car',
    baseFare: 5,
    perKm: 1.5,
    eta: '5 min',
  },
  {
    id: 'comfort',
    name: 'Comfort',
    description: 'Newer cars with AC',
    icon: 'car-side',
    baseFare: 8,
    perKm: 2.5,
    eta: '3 min',
  },
  {
    id: 'premium',
    name: 'Premium',
    description: 'Luxury vehicles',
    icon: 'car',
    baseFare: 15,
    perKm: 4,
    eta: '7 min',
  },
  {
    id: 'xl',
    name: 'XL',
    description: '6+ passengers',
    icon: 'van',
    baseFare: 12,
    perKm: 3.5,
    eta: '10 min',
  },
];

export const CuisineCategories = [
  { id: 'all', name: 'All', icon: 'utensils' },
  { id: 'arabic', name: 'Arabic', icon: 'coffee' },
  { id: 'fast-food', name: 'Fast Food', icon: 'hamburger' },
  { id: 'pizza', name: 'Pizza', icon: 'pizza-slice' },
  { id: 'asian', name: 'Asian', icon: 'bowl-rice' },
  { id: 'desserts', name: 'Desserts', icon: 'ice-cream' },
  { id: 'healthy', name: 'Healthy', icon: 'leaf' },
];

export const FeaturedRestaurants = [
  {
    id: '1',
    name: 'Al Baik',
    cuisine: 'Fast Food',
    rating: 4.8,
    reviews: 2340,
    deliveryTime: '25-35 min',
    deliveryFee: 0,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    promoted: true,
  },
  {
    id: '2',
    name: 'Pizza Hut',
    cuisine: 'Pizza',
    rating: 4.5,
    reviews: 1890,
    deliveryTime: '30-40 min',
    deliveryFee: 5,
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400',
    promoted: false,
  },
  {
    id: '3',
    name: 'KFC',
    cuisine: 'Fast Food',
    rating: 4.6,
    reviews: 3200,
    deliveryTime: '20-30 min',
    deliveryFee: 0,
    image: 'https://images.unsplash.com/photo-1513639776629-9269d0d905dd?w=400',
    promoted: true,
  },
  {
    id: '4',
    name: 'Al Tazaj',
    cuisine: 'Arabic',
    rating: 4.7,
    reviews: 1560,
    deliveryTime: '35-45 min',
    deliveryFee: 7,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
    promoted: false,
  },
];

export const PromotionalBanners = [
  {
    id: '1',
    title: '50% Off First Ride',
    subtitle: 'Use code: TATX50',
    gradient: ['#3B82F6', '#2563EB'],
    icon: 'car',
  },
  {
    id: '2',
    title: 'Free Delivery',
    subtitle: 'On orders over $30',
    gradient: ['#F97316', '#EA580C'],
    icon: 'utensils',
  },
  {
    id: '3',
    title: 'Grocery Deals',
    subtitle: 'Up to 40% off',
    gradient: ['#22C55E', '#16A34A'],
    icon: 'shopping-cart',
  },
];

export const RecentActivities = [
  {
    id: '1',
    type: 'ride',
    title: 'Ride to King Fahd Road',
    subtitle: 'Completed • Comfort',
    amount: -24.50,
    date: 'Today, 10:30 AM',
    icon: 'car',
    status: 'completed',
  },
  {
    id: '2',
    type: 'food',
    title: 'Order from Al Baik',
    subtitle: 'Delivered • 2 items',
    amount: -45.00,
    date: 'Yesterday, 8:15 PM',
    icon: 'utensils',
    status: 'completed',
  },
  {
    id: '3',
    type: 'grocery',
    title: 'Grocery Order',
    subtitle: 'Delivered • 8 items',
    amount: -120.00,
    date: 'Mar 10, 2024',
    icon: 'shopping-cart',
    status: 'completed',
  },
  {
    id: '4',
    type: 'courier',
    title: 'Package Delivery',
    subtitle: 'In Progress',
    amount: -15.00,
    date: 'Mar 9, 2024',
    icon: 'package',
    status: 'in-progress',
  },
];

export const ProfileMenuItems = [
  {
    id: 'wallet',
    title: 'Wallet',
    subtitle: '$245.50 balance',
    icon: 'wallet',
    color: '#22C55E',
  },
  {
    id: 'ride-history',
    title: 'Ride History',
    subtitle: '24 rides',
    icon: 'clock',
    color: '#3B82F6',
  },
  {
    id: 'order-history',
    title: 'Order History',
    subtitle: '56 orders',
    icon: 'shopping-bag',
    color: '#F97316',
  },
  {
    id: 'addresses',
    title: 'Saved Addresses',
    subtitle: '3 addresses',
    icon: 'map-pin',
    color: '#8B5CF6',
  },
  {
    id: 'payment',
    title: 'Payment Methods',
    subtitle: '2 cards',
    icon: 'credit-card',
    color: '#06B6D4',
  },
  {
    id: 'settings',
    title: 'Settings',
    subtitle: 'Notifications, Privacy',
    icon: 'settings',
    color: '#6B7280',
  },
  {
    id: 'support',
    title: 'Support',
    subtitle: 'Help & FAQ',
    icon: 'headphones',
    color: '#EC4899',
  },
];

export const Languages = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
];
