name: Publish Preview Update

on:
  push:
    branches: ['main']

jobs:
  publish_preview_update:
    type: update
    params:
      channel: preview
      message: 'Preview update from EAS Workflow'
